// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvvIHvau_dEJwGiV0CVPq8nfJlTzbKF5o',
    appId: '1:102403684777:web:748c1144975524de56acb8',
    messagingSenderId: '102403684777',
    projectId: 'zona-jas',
    authDomain: 'zona-jas.firebaseapp.com',
    storageBucket: 'zona-jas.appspot.com',
    measurementId: 'G-XKN7FR9E28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGhk7rqpPOEQbF1YviPeEsKCajSWelng',
    appId: '1:102403684777:android:4e16ee409d279b4656acb8',
    messagingSenderId: '102403684777',
    projectId: 'zona-jas',
    storageBucket: 'zona-jas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9UbG0oxlU6stdeQcPqOVN7IkSG6DlsE',
    appId: '1:102403684777:ios:1abb5e6ac41e292256acb8',
    messagingSenderId: '102403684777',
    projectId: 'zona-jas',
    storageBucket: 'zona-jas.appspot.com',
    iosBundleId: 'com.example.zonajas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9UbG0oxlU6stdeQcPqOVN7IkSG6DlsE',
    appId: '1:102403684777:ios:5d0d6d0f44a2a9ba56acb8',
    messagingSenderId: '102403684777',
    projectId: 'zona-jas',
    storageBucket: 'zona-jas.appspot.com',
    iosBundleId: 'com.example.zonajas.RunnerTests',
  );
}
